apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    type: testing
spec:
  containers:
    - name: db
      image: postgres:16.1-alpine3.19
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
      ports: 
        - containerPort: 5432