apiVersion: v1
kind: Pod
metadata:
  name: result
  labels:
    type: testing
spec:
  containers:
    - name: result
      image: dockersamples/examplevotingapp_result
      ports: 
        - containerPort: 80