apiVersion: v1
kind: Pod
metadata:
  name: vote
  labels:
    type: vote
spec:
  containers:
    - name: vote
      image: dockersamples/examplevotingapp_vote
      ports:  
        - containerPort: 80