apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: pod
    type: testing

spec:
  containers:
  # redis
  -  name: redis
     image: redis:7.2.3-alpine
     ports:
       - containerPort: 6379
  # Postgres
  - name: db
    image: postgres:16.1-alpine3.19
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
    ports:
      - containerPort: 5432
  - name: result
    image: dockersamples/examplevotingapp_result
    ports: 
      - containerPort: 80
  - name: vote
    image: dockersamples/examplevotingapp_vote
    ports: 
      - containerPort: 80
  - name: worker
    image: dockersamples/examplevotingapp_worker
    # no need to expose port

  