apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappDeployment
  labels:
    type: production
spec:
  selector:
    matchLabels:
      type: production
  replicas: 6
  template:
    metadata:
      name: myapp
      labels:
        type: production
    spec:
      containers:
      -  name: myappNginx
         image: nginx