apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    labels:
      type: production
      name: customer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009