apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    type: prod
spec:
  selector:
    labels:
      type: prod
  replicas: 4
  template:
    metadata:
      name: nginx
      labels:
        type: prod
    spec:
      containers:
      -  name: nginx
         image: nginx
      ports:
      - containerPort: 80
      - name: nginx
        image: nginx