apiVersion: v1
kind: Pod
metadata:
  labels:
    app: db
  name: db
spec:
  containers:
    - name: db
      image: postgres:16.1-alpine3.19
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
      ports: 
        - containerPort: 5432
          name: postgres
  #     volumeMounts:
  #     - mountPath: /var/lib/postgresql/data
  #       name: db-data
  # volumes:
  # - name: db-data
  #   emptyDir: {}