apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    type: testing
spec:
  selector:
    type: testing
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
